# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json
# Created using wingetcreate

PackageIdentifier: Iriun.IriunWebcam
PackageVersion: 2.8.1
InstallerLocale: en-US
MinimumOSVersion: 10.0.0.0
InstallerType: inno
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.DotNet.Runtime.3_1
AppsAndFeaturesEntries:
  - DisplayName: Iriun Webcam version 2.7.5
Installers:
- Architecture: x86
  InstallerUrl: https://1758658189.rsc.cdn77.org/IriunWebcam-2.8.1.exe
  InstallerSha256: E690D0CD760642CB713E4716EDB7B400E8AA947FCD0B208D4C5CC48B85CC55C8	
ManifestType: installer
ManifestVersion: 1.2.0
